"""автоматическая миграция

Revision ID: 128e7881632f
Revises: bfa6da760125
Create Date: 2026-03-18 14:02:55.857159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '128e7881632f'
down_revision = 'bfa6da760125'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('special_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person_data', schema=None) as batch_op:
        batch_op.drop_column('special_notes')

    # ### end Alembic commands ###
