"""автоматическая миграция

Revision ID: 154f66f9a777
Revises: f7d32470af07
Create Date: 2026-03-18 20:09:29.015747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '154f66f9a777'
down_revision = 'f7d32470af07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relatives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('p1_track_number', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('p1_track_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('p2_track_number', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('p2_track_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('p3_track_number', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('p3_track_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('p4_track_number', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('p4_track_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('p5_track_number', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('p5_track_date', sa.Date(), nullable=True))
        batch_op.drop_column('track_date')
        batch_op.drop_column('track_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relatives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('track_number', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('track_date', sa.DATE(), nullable=True))
        batch_op.drop_column('p5_track_date')
        batch_op.drop_column('p5_track_number')
        batch_op.drop_column('p4_track_date')
        batch_op.drop_column('p4_track_number')
        batch_op.drop_column('p3_track_date')
        batch_op.drop_column('p3_track_number')
        batch_op.drop_column('p2_track_date')
        batch_op.drop_column('p2_track_number')
        batch_op.drop_column('p1_track_date')
        batch_op.drop_column('p1_track_number')

    # ### end Alembic commands ###
