"""автоматическая миграция

Revision ID: bfa6da760125
Revises: 
Create Date: 2026-03-17 19:30:21.123800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfa6da760125'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relatives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('p1_size', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('p1_period_from', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('p1_period_to', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('p1_period_indefinite', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('p2_size', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('p2_period_from', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('p2_period_to', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('p2_period_indefinite', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('p3_size', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('p3_period_from', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('p3_period_to', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('p3_period_indefinite', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('p4_size', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('p4_period_from', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('p4_period_to', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('p4_period_indefinite', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('p5_size', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('p5_period_from', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('p5_period_to', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('p5_period_indefinite', sa.Boolean(), nullable=True))
        batch_op.drop_column('period_assignment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relatives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('period_assignment', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('p5_period_indefinite')
        batch_op.drop_column('p5_period_to')
        batch_op.drop_column('p5_period_from')
        batch_op.drop_column('p5_size')
        batch_op.drop_column('p4_period_indefinite')
        batch_op.drop_column('p4_period_to')
        batch_op.drop_column('p4_period_from')
        batch_op.drop_column('p4_size')
        batch_op.drop_column('p3_period_indefinite')
        batch_op.drop_column('p3_period_to')
        batch_op.drop_column('p3_period_from')
        batch_op.drop_column('p3_size')
        batch_op.drop_column('p2_period_indefinite')
        batch_op.drop_column('p2_period_to')
        batch_op.drop_column('p2_period_from')
        batch_op.drop_column('p2_size')
        batch_op.drop_column('p1_period_indefinite')
        batch_op.drop_column('p1_period_to')
        batch_op.drop_column('p1_period_from')
        batch_op.drop_column('p1_size')

    # ### end Alembic commands ###
