"""автоматическая миграция

Revision ID: f7d32470af07
Revises: 128e7881632f
Create Date: 2026-03-18 16:49:14.110204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7d32470af07'
down_revision = '128e7881632f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ru_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('executor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('executor_text', sa.String(length=200), nullable=True))
        batch_op.create_foreign_key(
            'fk_ru_records_executor_id',  # Добавлено имя
            'relatives',
            ['executor_id'],
            ['id']
        )
        batch_op.drop_column('executor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ru_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('executor', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_constraint('fk_ru_records_executor_id', type_='foreignkey')
        batch_op.drop_column('executor_text')
        batch_op.drop_column('executor_id')
    # ### end Alembic commands ###

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ru_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('executor', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('executor_text')
        batch_op.drop_column('executor_id')

    # ### end Alembic commands ###
